/**
 * Domain Category Mapping — maps popular domains to interest categories
 * Used for history analysis to infer user interests
 */

const DOMAIN_CATEGORIES = {
  // Technology / Development
  'github.com': 'Technology/Development',
  'gitlab.com': 'Technology/Development',
  'bitbucket.org': 'Technology/Development',
  'stackoverflow.com': 'Technology/Development',
  'stackexchange.com': 'Technology/Development',
  'developer.mozilla.org': 'Technology/Development',
  'docs.python.org': 'Technology/Development',
  'nodejs.org': 'Technology/Development',
  'npmjs.com': 'Technology/Development',
  'pypi.org': 'Technology/Development',
  'crates.io': 'Technology/Development',
  'rust-lang.org': 'Technology/Development',
  'go.dev': 'Technology/Development',
  'typescriptlang.org': 'Technology/Development',
  'reactjs.org': 'Technology/Development',
  'vuejs.org': 'Technology/Development',
  'angular.io': 'Technology/Development',
  'svelte.dev': 'Technology/Development',
  'nextjs.org': 'Technology/Development',
  'vercel.com': 'Technology/Development',
  'netlify.com': 'Technology/Development',
  'heroku.com': 'Technology/Development',
  'aws.amazon.com': 'Technology/Cloud',
  'cloud.google.com': 'Technology/Cloud',
  'azure.microsoft.com': 'Technology/Cloud',
  'digitalocean.com': 'Technology/Cloud',
  'codepen.io': 'Technology/Development',
  'codesandbox.io': 'Technology/Development',
  'replit.com': 'Technology/Development',
  'jsfiddle.net': 'Technology/Development',
  'dev.to': 'Technology/Blog',
  'hashnode.dev': 'Technology/Blog',
  'freecodecamp.org': 'Technology/Education',
  'codecademy.com': 'Technology/Education',
  'leetcode.com': 'Technology/Development',
  'hackerrank.com': 'Technology/Development',
  'kaggle.com': 'Technology/Data Science',
  'huggingface.co': 'Technology/AI',
  'openai.com': 'Technology/AI',
  'anthropic.com': 'Technology/AI',
  'docker.com': 'Technology/DevOps',
  'kubernetes.io': 'Technology/DevOps',

  // Tech News
  'techcrunch.com': 'Technology/News',
  'theverge.com': 'Technology/News',
  'arstechnica.com': 'Technology/News',
  'wired.com': 'Technology/News',
  'engadget.com': 'Technology/News',
  'gizmodo.com': 'Technology/News',
  'hackernews.com': 'Technology/News',
  'news.ycombinator.com': 'Technology/News',
  'slashdot.org': 'Technology/News',
  'macrumors.com': 'Technology/News',
  '9to5mac.com': 'Technology/News',
  'tomshardware.com': 'Technology/Hardware',
  'anandtech.com': 'Technology/Hardware',

  // Social Media
  'twitter.com': 'Social Media',
  'x.com': 'Social Media',
  'facebook.com': 'Social Media',
  'instagram.com': 'Social Media',
  'linkedin.com': 'Professional/Career',
  'tiktok.com': 'Social Media',
  'snapchat.com': 'Social Media',
  'pinterest.com': 'Social Media',
  'reddit.com': 'Social/Forum',
  'old.reddit.com': 'Social/Forum',
  'tumblr.com': 'Social Media',
  'mastodon.social': 'Social Media',
  'bsky.app': 'Social Media',
  'threads.net': 'Social Media',
  'discord.com': 'Social/Communication',
  'slack.com': 'Professional/Communication',
  'telegram.org': 'Social/Communication',
  'web.telegram.org': 'Social/Communication',
  'whatsapp.com': 'Social/Communication',
  'web.whatsapp.com': 'Social/Communication',
  'signal.org': 'Social/Communication',
  'quora.com': 'Social/Q&A',

  // News
  'nytimes.com': 'News',
  'washingtonpost.com': 'News',
  'bbc.com': 'News',
  'bbc.co.uk': 'News',
  'cnn.com': 'News',
  'reuters.com': 'News',
  'apnews.com': 'News',
  'theguardian.com': 'News',
  'bloomberg.com': 'News/Finance',
  'ft.com': 'News/Finance',
  'wsj.com': 'News/Finance',
  'economist.com': 'News',
  'politico.com': 'News/Politics',
  'axios.com': 'News',
  'nbcnews.com': 'News',
  'abcnews.go.com': 'News',
  'foxnews.com': 'News',
  'aljazeera.com': 'News',
  'dw.com': 'News',
  'france24.com': 'News',
  'news.sky.com': 'News',
  'theatlantic.com': 'News/Magazine',
  'newyorker.com': 'News/Magazine',
  'vox.com': 'News',
  'vice.com': 'News',
  'buzzfeed.com': 'News/Entertainment',
  'huffpost.com': 'News',

  // Shopping
  'amazon.com': 'Shopping',
  'amazon.co.uk': 'Shopping',
  'amazon.de': 'Shopping',
  'ebay.com': 'Shopping',
  'walmart.com': 'Shopping',
  'target.com': 'Shopping',
  'bestbuy.com': 'Shopping/Electronics',
  'newegg.com': 'Shopping/Electronics',
  'etsy.com': 'Shopping/Handmade',
  'aliexpress.com': 'Shopping',
  'alibaba.com': 'Shopping/B2B',
  'shopify.com': 'Shopping/Platform',
  'wayfair.com': 'Shopping/Home',
  'ikea.com': 'Shopping/Home',
  'zappos.com': 'Shopping/Fashion',
  'nordstrom.com': 'Shopping/Fashion',
  'zara.com': 'Shopping/Fashion',
  'hm.com': 'Shopping/Fashion',
  'asos.com': 'Shopping/Fashion',
  'nike.com': 'Shopping/Sports',
  'adidas.com': 'Shopping/Sports',
  'costco.com': 'Shopping',
  'homedepot.com': 'Shopping/Home',
  'lowes.com': 'Shopping/Home',
  'sephora.com': 'Shopping/Beauty',
  'ulta.com': 'Shopping/Beauty',

  // Entertainment
  'youtube.com': 'Entertainment/Video',
  'netflix.com': 'Entertainment/Streaming',
  'hulu.com': 'Entertainment/Streaming',
  'disneyplus.com': 'Entertainment/Streaming',
  'hbomax.com': 'Entertainment/Streaming',
  'max.com': 'Entertainment/Streaming',
  'primevideo.com': 'Entertainment/Streaming',
  'peacocktv.com': 'Entertainment/Streaming',
  'crunchyroll.com': 'Entertainment/Anime',
  'twitch.tv': 'Entertainment/Gaming',
  'vimeo.com': 'Entertainment/Video',
  'dailymotion.com': 'Entertainment/Video',
  'spotify.com': 'Entertainment/Music',
  'open.spotify.com': 'Entertainment/Music',
  'music.apple.com': 'Entertainment/Music',
  'soundcloud.com': 'Entertainment/Music',
  'bandcamp.com': 'Entertainment/Music',
  'tidal.com': 'Entertainment/Music',
  'deezer.com': 'Entertainment/Music',
  'imdb.com': 'Entertainment/Movies',
  'rottentomatoes.com': 'Entertainment/Movies',
  'letterboxd.com': 'Entertainment/Movies',

  // Gaming
  'store.steampowered.com': 'Gaming',
  'steampowered.com': 'Gaming',
  'epicgames.com': 'Gaming',
  'gog.com': 'Gaming',
  'ign.com': 'Gaming/News',
  'gamespot.com': 'Gaming/News',
  'kotaku.com': 'Gaming/News',
  'polygon.com': 'Gaming/News',
  'pcgamer.com': 'Gaming/News',
  'xbox.com': 'Gaming',
  'playstation.com': 'Gaming',
  'nintendo.com': 'Gaming',
  'roblox.com': 'Gaming',

  // Finance
  'chase.com': 'Finance/Banking',
  'bankofamerica.com': 'Finance/Banking',
  'wellsfargo.com': 'Finance/Banking',
  'capitalone.com': 'Finance/Banking',
  'paypal.com': 'Finance/Payments',
  'venmo.com': 'Finance/Payments',
  'stripe.com': 'Finance/Payments',
  'robinhood.com': 'Finance/Investing',
  'fidelity.com': 'Finance/Investing',
  'vanguard.com': 'Finance/Investing',
  'schwab.com': 'Finance/Investing',
  'etrade.com': 'Finance/Investing',
  'coinbase.com': 'Finance/Crypto',
  'binance.com': 'Finance/Crypto',
  'kraken.com': 'Finance/Crypto',
  'mint.com': 'Finance/Budgeting',
  'ynab.com': 'Finance/Budgeting',
  'creditkarma.com': 'Finance/Credit',
  'nerdwallet.com': 'Finance/Advice',
  'investopedia.com': 'Finance/Education',
  'yahoo.com/finance': 'Finance/News',
  'finance.yahoo.com': 'Finance/News',
  'marketwatch.com': 'Finance/News',
  'seekingalpha.com': 'Finance/Investing',
  'fool.com': 'Finance/Investing',

  // Health
  'webmd.com': 'Health',
  'mayoclinic.org': 'Health',
  'healthline.com': 'Health',
  'nih.gov': 'Health/Research',
  'drugs.com': 'Health/Pharmacy',
  'myfitnesspal.com': 'Health/Fitness',
  'strava.com': 'Health/Fitness',
  'fitbit.com': 'Health/Fitness',
  'peloton.com': 'Health/Fitness',
  'calm.com': 'Health/Wellness',
  'headspace.com': 'Health/Wellness',

  // Education
  'coursera.org': 'Education',
  'edx.org': 'Education',
  'udemy.com': 'Education',
  'udacity.com': 'Education',
  'khanacademy.org': 'Education',
  'skillshare.com': 'Education',
  'masterclass.com': 'Education',
  'pluralsight.com': 'Education/Tech',
  'lynda.com': 'Education',
  'duolingo.com': 'Education/Languages',
  'wikipedia.org': 'Education/Reference',
  'en.wikipedia.org': 'Education/Reference',
  'britannica.com': 'Education/Reference',
  'scholar.google.com': 'Education/Research',
  'researchgate.net': 'Education/Research',
  'academia.edu': 'Education/Research',
  'mit.edu': 'Education/University',
  'stanford.edu': 'Education/University',
  'harvard.edu': 'Education/University',

  // Productivity
  'docs.google.com': 'Productivity',
  'drive.google.com': 'Productivity',
  'sheets.google.com': 'Productivity',
  'calendar.google.com': 'Productivity',
  'mail.google.com': 'Productivity/Email',
  'gmail.com': 'Productivity/Email',
  'outlook.com': 'Productivity/Email',
  'outlook.live.com': 'Productivity/Email',
  'notion.so': 'Productivity',
  'trello.com': 'Productivity',
  'asana.com': 'Productivity',
  'monday.com': 'Productivity',
  'jira.atlassian.com': 'Productivity/Project',
  'confluence.atlassian.com': 'Productivity/Wiki',
  'airtable.com': 'Productivity',
  'figma.com': 'Design/Tool',
  'canva.com': 'Design/Tool',
  'miro.com': 'Productivity/Collaboration',
  'zoom.us': 'Productivity/Meeting',
  'teams.microsoft.com': 'Productivity/Meeting',
  'meet.google.com': 'Productivity/Meeting',
  'dropbox.com': 'Productivity/Storage',
  'box.com': 'Productivity/Storage',

  // Travel
  'booking.com': 'Travel',
  'airbnb.com': 'Travel',
  'expedia.com': 'Travel',
  'tripadvisor.com': 'Travel',
  'kayak.com': 'Travel',
  'skyscanner.com': 'Travel/Flights',
  'google.com/flights': 'Travel/Flights',
  'maps.google.com': 'Travel/Maps',
  'uber.com': 'Travel/Rideshare',
  'lyft.com': 'Travel/Rideshare',

  // Food
  'doordash.com': 'Food/Delivery',
  'ubereats.com': 'Food/Delivery',
  'grubhub.com': 'Food/Delivery',
  'yelp.com': 'Food/Reviews',
  'allrecipes.com': 'Food/Cooking',
  'foodnetwork.com': 'Food/Cooking',
  'seriouseats.com': 'Food/Cooking',

  // Real Estate
  'zillow.com': 'Real Estate',
  'realtor.com': 'Real Estate',
  'redfin.com': 'Real Estate',
  'trulia.com': 'Real Estate',
  'apartments.com': 'Real Estate/Rental',

  // Automotive
  'cars.com': 'Automotive',
  'autotrader.com': 'Automotive',
  'carvana.com': 'Automotive',
  'edmunds.com': 'Automotive',
  'kbb.com': 'Automotive',
  'tesla.com': 'Automotive',

  // Job/Career
  'indeed.com': 'Career/Job Search',
  'glassdoor.com': 'Career/Job Search',
  'ziprecruiter.com': 'Career/Job Search',
  'monster.com': 'Career/Job Search',
  'angel.co': 'Career/Startups',
  'levels.fyi': 'Career/Salary',

  // Media / Blog
  'medium.com': 'Media/Blog',
  'substack.com': 'Media/Newsletter',
  'wordpress.com': 'Media/Blog',
  'blogger.com': 'Media/Blog',

  // Government / Legal
  'irs.gov': 'Government/Tax',
  'ssa.gov': 'Government',
  'usa.gov': 'Government',
  'gov.uk': 'Government',

  // Dating
  'tinder.com': 'Dating',
  'bumble.com': 'Dating',
  'hinge.co': 'Dating',
  'match.com': 'Dating',
  'okcupid.com': 'Dating',

  // Search
  'google.com': 'Search',
  'bing.com': 'Search',
  'duckduckgo.com': 'Search',
  'brave.com': 'Search',
  'ecosia.org': 'Search',
  'startpage.com': 'Search',

  // Adult (detected but not exposed in detail)
  'pornhub.com': 'Adult',
  'xvideos.com': 'Adult',
  'xhamster.com': 'Adult',
  'onlyfans.com': 'Adult',
};

function categorizeUrl(url) {
  try {
    const hostname = new URL(url).hostname.replace(/^www\./, '');
    // Direct match
    if (DOMAIN_CATEGORIES[hostname]) return DOMAIN_CATEGORIES[hostname];
    // Try parent domain
    const parts = hostname.split('.');
    if (parts.length > 2) {
      const parent = parts.slice(-2).join('.');
      if (DOMAIN_CATEGORIES[parent]) return DOMAIN_CATEGORIES[parent];
    }
    return null;
  } catch {
    return null;
  }
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { DOMAIN_CATEGORIES, categorizeUrl };
}
