/**
 * Known Tracker Database — domains used for advertising, analytics, and data collection
 */

const KNOWN_TRACKERS = {
  advertising: [
    'doubleclick.net',
    'googlesyndication.com',
    'googleadservices.com',
    'googleads.g.doubleclick.net',
    'pagead2.googlesyndication.com',
    'adservice.google.com',
    'facebook.net',
    'fbcdn.net',
    'facebook.com',
    'amazon-adsystem.com',
    'criteo.com',
    'criteo.net',
    'outbrain.com',
    'taboola.com',
    'adnxs.com',
    'rubiconproject.com',
    'pubmatic.com',
    'openx.net',
    'casalemedia.com',
    'advertising.com',
    'adsrvr.org',
    'adroll.com',
    'bidswitch.net',
    'mopub.com',
    'unity3d.com',
    'applovin.com',
    'ironSource.com',
    'chartboost.com',
    'vungle.com',
    'smaato.net',
    'inmobi.com',
    'media.net',
    'sharethrough.com',
    'triplelift.com',
    'sovrn.com',
    'undertone.com',
    'yieldmo.com',
    'smartadserver.com',
    'indexexchange.com',
    'spotxchange.com',
    'contextweb.com',
    'conversantmedia.com',
    'rhythmone.com',
    'districtm.io',
    'emxdigital.com',
    'gumgum.com',
    'kargo.com',
    'nativo.com',
    'revcontent.com',
    'mgid.com',
    'yahoo.com',
    'oath.com',
  ],
  analytics: [
    'google-analytics.com',
    'googletagmanager.com',
    'googletagservices.com',
    'analytics.google.com',
    'hotjar.com',
    'hotjar.io',
    'mixpanel.com',
    'segment.com',
    'segment.io',
    'amplitude.com',
    'fullstory.com',
    'mouseflow.com',
    'crazyegg.com',
    'optimizely.com',
    'heapanalytics.com',
    'heap.io',
    'clarity.ms',
    'newrelic.com',
    'nr-data.net',
    'sentry.io',
    'bugsnag.com',
    'logrocket.com',
    'datadog-agent.com',
    'pendo.io',
    'walkme.com',
    'appcues.com',
    'intercom.io',
    'intercomcdn.com',
    'userpilot.com',
    'kissmetrics.com',
    'chartbeat.com',
    'chartbeat.net',
    'parsely.com',
    'parse.ly',
    'quantserve.com',
    'scorecardresearch.com',
    'comscore.com',
    'omtrdc.net',
    'demdex.net',
    'adobedtm.com',
    'matomo.cloud',
    'plausible.io',
  ],
  social: [
    'facebook.com',
    'fbcdn.net',
    'facebook.net',
    'twitter.com',
    'twimg.com',
    'x.com',
    'linkedin.com',
    'licdn.com',
    'instagram.com',
    'cdninstagram.com',
    'tiktok.com',
    'tiktokcdn.com',
    'snap.com',
    'snapchat.com',
    'sc-cdn.net',
    'pinterest.com',
    'pinimg.com',
    'reddit.com',
    'redditmedia.com',
    'redditstatic.com',
    'tumblr.com',
    'discord.com',
    'discordapp.com',
  ],
  data_brokers: [
    'bluekai.com',
    'exelator.com',
    'acxiom.com',
    'liveramp.com',
    'rlcdn.com',
    'lotame.com',
    'crwdcntrl.net',
    'bombora.com',
    'intentiq.com',
    'zeotap.com',
    'eyeota.com',
    'adsymptotic.com',
    'tapad.com',
    'drawbridge.com',
    'crosswise.com',
    'oracle.com',
    'addthis.com',
    'sharethis.com',
    'bounceexchange.com',
    'narrativ.com',
    'skimresources.com',
    'skimlinks.com',
  ],
  fingerprinting: [
    'fingerprintjs.com',
    'fpjs.io',
    'maxmind.com',
    'ipinfo.io',
    'ipapi.com',
    'ipify.org',
    'deviceatlas.com',
    'scientiamobile.com',
    '51degrees.com',
  ],
  consent_management: [
    'onetrust.com',
    'cookiebot.com',
    'trustarc.com',
    'quantcast.com',
    'evidon.com',
    'cookiepro.com',
    'consentmanager.net',
    'didomi.io',
    'usercentrics.com',
  ],
};

// Flatten for quick lookup
const ALL_TRACKER_DOMAINS = {};
for (const [category, domains] of Object.entries(KNOWN_TRACKERS)) {
  for (const domain of domains) {
    ALL_TRACKER_DOMAINS[domain] = category;
  }
}

function getTrackerCategory(domain) {
  if (!domain) return null;
  // Check exact match
  if (ALL_TRACKER_DOMAINS[domain]) return ALL_TRACKER_DOMAINS[domain];
  // Check parent domain
  const parts = domain.split('.');
  for (let i = 1; i < parts.length - 1; i++) {
    const parent = parts.slice(i).join('.');
    if (ALL_TRACKER_DOMAINS[parent]) return ALL_TRACKER_DOMAINS[parent];
  }
  return null;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { KNOWN_TRACKERS, ALL_TRACKER_DOMAINS, getTrackerCategory };
}
